decml/decml/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('main.urls', 'main'), namespace='main'))
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

decml/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('contact/', views.contact, name='contact'),
    path('', views.home, name='home'),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('thank-you/', views.thank_you, name='thank_you'),
    ]

decml/main/models.py
from django.db import models


class Emails(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    company = models.CharField(max_length=100)
    website = models.CharField(max_length=100)
    message = models.TextField(max_length=1000)
    email = models.EmailField()
    created_at = models.DateTimeField(auto_now_add=True,)


    def __str__(self):
        return f"Contact form completion from {self.first_name} - {self.email}"

decml/main/forms.py
from django import forms


class ContactForm(forms.Form):
    first_name = forms.CharField(label="First name", max_length=100, required=True, widget=forms.TextInput(attrs={"class": "form-control"}))
    last_name = forms.CharField(label="Last name", max_length=100, required=True, widget=forms.TextInput(attrs={"class": "form-control"}))
    company = forms.CharField(label="Company", max_length=100, required=True, widget=forms.TextInput(attrs={"class": "form-control"}))
    website = forms.CharField(label="Your website", max_length=100, widget=forms.URLInput(attrs={"class": "form-control"}))
    email = forms.EmailField(label="Your business email", max_length=100, required=True, widget=forms.EmailInput(attrs={"class": "form-control"}))
    message = forms.CharField(label="Your message", widget=forms.Textarea(attrs={"class": "form-control"}))

decml/main/views.py
from django.shortcuts import render, redirect
from .forms import ContactForm
from django.core.mail import send_mail
from .models import Emails



def contact(request):
    if request.method == "POST":
        contact_form = ContactForm(request.POST)
        if contact_form.is_valid():
            first = contact_form.cleaned_data["first_name"]
            last = contact_form.cleaned_data["last_name"]
            email = contact_form.cleaned_data["email"]
            website = contact_form.cleaned_data["website"]
            company = contact_form.cleaned_data["company"]
            message = contact_form.cleaned_data["message"]
            send_mail(
                subject="decml Contact Form Completion",
                message=f"Sender: {first} {last}"
                f"Email: {email}"
                f"Website: {website}"
                f"Company: {company}"
                f"{message}",
                from_email="omarisemail@gmail.com",
                recipient_list=["omarisemail@gmail.com"],
                fail_silently=False
            )
            email = Emails(
                first_name=first,
                last_name=last,
                email=email,
                company=company,
                website=website,
                message=message
            )
            email.save()
            return redirect("main:home")
    else:
        contact_form = ContactForm()
    return render(request, 'main/contact.html', {
        'form': contact_form
    })


def portfolio(request):
    return render(request, 'main/portfolio.html')


def home(request):
    return render(request, 'main/home.html')


def thank_you(request):
    return render(request, 'main/thank_you.html')

decml/main/templates/main/base.html
{%  load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.1.1">
    <link rel="shortcut icon" type="image/png" href="{% static 'main/favicon.ico' %}"/>
    {% block add_meta %}{% endblock %}
    <title>decml | {% block title %}{% endblock %}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/cover/">

    <!-- Bootstrap core CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="{% static 'main/cover.css' %}" rel="stylesheet">
  </head>
  <body class="text-center">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="masthead mb-auto">
    <div class="inner">
      <h3 class="masthead-brand">decml</h3>
      <nav class="nav nav-masthead justify-content-center">
        {% block nav %}
        {% endblock %}
      </nav>
    </div>
  </header>

  <main role="main" class="inner cover">
    {% block page_content %}
    {% endblock %}
  </main>

  <footer class="mastfoot mt-auto">
    <div class="inner">
    </div>
  </footer>
</div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

decml/main/templates/main/contact.html
{% extends "main/base.html" %}
{% block title %}Contact Us{% endblock %}
{% block nav %}
<a class="nav-link" href="{% url 'main:home' %}">Home</a>
<a class="nav-link" href="{% url 'main:portfolio' %}">Portfolio</a>
<a class="nav-link active" href="{% url 'main:contact' %}">Contact</a>
{% endblock %}

{% block page_content %}
<h1> Contact Form</h1>
<div class="form-group">
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-secondary">Submit</button>
    </form>
</div>
{% endblock %}

decml/main/templates/main/home.html
{% extends "main/base.html" %}
{% block title %}Custom AI solutions for small businesses{% endblock %}

{% block nav %}
<a class="nav-link active" href="{% url 'main:home' %}">Home</a>
<a class="nav-link" href="{% url 'main:portfolio' %}">Portfolio</a>
<a class="nav-link" href="{% url 'main:contact' %}">Contact</a>
{% endblock %}

    {% block page_content %}
    {% load static %}
    <img src="{% static 'main/decml_logo.png' %}" alt="decml logo" height="150
">
    <h3 class="cover-heading">AI Automation Specialists</h3>
    <p>decml: empowering small businesses with custom AI solutions to automate tasks and drive growth.</p>
    <p class="lead"></p>
    <p class="lead">
      <a href="#" class="btn btn-lg btn-secondary">Learn more</a>
    </p>
    {% endblock %}

decml/main/templates/main/portfolio.html
{% extends "main/base.html" %}
{% block title %}Portfolio{% endblock %}

{% block nav %}
<a class="nav-link" href="{% url 'main:home' %}">Home</a>
<a class="nav-link active" href="{% url 'main:portfolio' %}">Portfolio</a>
<a class="nav-link" href="{% url 'main:contact' %}">Contact</a>
{% endblock %}

    {% block page_content %}
    {% load static %}
    <div class="row">
      <div class="col-lg-4">
        <img src="{% static 'main/chat_app.jpg' %}" class="bd-placeholder-img rounded-circle" style="object-fit: cover;" width="140" height="140" alt="Description of image">
        <h4 class="fw-normal">Electrician's Chatbot</h4>
        <p>Chatbot built with RAG pipeline using LangChain, OpenAI, Pinecone and Django</p>
        <p><a class="btn btn-secondary" href="http://ec2-13-41-230-193.eu-west-2.compute.amazonaws.com:8000">View app »</a></p>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4">
        <img src="{% static 'main/image_classifier_app.jpg' %}" class="bd-placeholder-img rounded-circle" style="object-fit: cover;" width="140" height="140" alt="Description of image">
        <h4 class="fw-normal">Image Classifier App</h4>
        <p>Proof of concept image classification streamlit application using Keras neural network model</p>
        <p><a class="btn btn-secondary" href="http://ec2-13-43-89-20.eu-west-2.compute.amazonaws.com:8501">View app »</a></p>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4">
       <img src="{% static 'main/soft_dev_salary_app.jpg' %}" class="bd-placeholder-img rounded-circle" style="object-fit: cover;" width="140" height="140" alt="Description of image">
        <h4 class="fw-normal">Salary Prediction App</h4>
        <p>Proof of concept machine learning streamlit application trained with scikit-learn</p>
        <p><a class="btn btn-secondary" href="http://ec2-13-42-15-185.eu-west-2.compute.amazonaws.com:8501">View app »</a></p>
      </div><!-- /.col-lg-4 -->
    </div>
    {% endblock %}

decml/main/templates/main/thank_you.html
{% extends "main/base.html" %}
{% block title %}Thank You{% endblock %}
{% block add_meta %}<meta http-equiv="refresh" content="3;url={% url 'main:home' %}">{% endblock %}

{% block nav %}
<a class="nav-link" href="{% url 'main:home' %}">Home</a>
<a class="nav-link" href="{% url 'main:portfolio' %}">Portfolio</a>
<a class="nav-link" href="{% url 'main:contact' %}">Contact</a>
{% endblock %}

    {% block page_content %}
    {% load static %}
    <h1>Thank you for enquiry</h1>
    <p>We will be in touch within 48 hours</p>
    {% endblock %}